apiVersion: batch/v1
kind: Job
metadata:
  name: hello-ignite
spec:
  template:
    metadata:
      name: hello-ignite
    spec:
      restartPolicy: OnFailure
      containers:
      - name: hello-ignite
        image: lreimer/hello-ignite:1.0.0
        env:
        - name: CONFIG_URI
          value: file:///app/data2day/config/kubernetes-ignite.xml
        - name: JAVA_OPTS
          value: -Xmx256m
        volumeMounts:
        - mountPath: /app/data2day/config
          name: ignite-config
      volumes:
      - name: ignite-config
        configMap:
          name: kubernetes-ignite-xml
