apiVersion: batch/v1
kind: Job
metadata:
  name: service-grid
spec:
  template:
    metadata:
      name: service-grid
    spec:
      restartPolicy: OnFailure
      containers:
      - name: service-grid
        image: lreimer/service-grid:1.0.2
        env:
        - name: CONFIG_URI
          value: file:///app/data2day/config/kubernetes-ignite.xml
        - name: JAVA_OPTS
          value: -Xmx256m
        volumeMounts:
        - mountPath: /app/data2day/config
          name: ignite-config
      volumes:
      - name: ignite-config
        configMap:
          name: kubernetes-ignite-xml
